[package]
name = "ernisto/fusor-lib"
version = "0.0.4"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

exclude = [
    # settings
    "aftman.toml",
    "stylua.toml",
    # "wally.toml",
    "pesde.yaml",

    ".darklua.json",
    ".gitignore",
    ".luaurc",
    ".vscode",

    # misc files
    "sourcemap.json",
    "tests",
    "build",
]

[dependencies]
